### ISSUE TITLE
Bad json-iterator release on 1.8

### ISSUE THREAD

**Issue by cjschaef** [kubernetes/test-infra#7183]
When attempting to fetch `test-infra` and install its dependencies, an error is encountered due to a bug in the `json-iterator` release:
```
bash-4.3# go version
go version go1.8.7 linux/amd64

bash-4.3# go get -u k8s.io/test-infra/kubetest
# k8s.io/test-infra/vendor/github.com/json-iterator/go
src/k8s.io/test-infra/vendor/github.com/json-iterator/go/config.go:107: undefined: sync.Map
```
This looks to be due to the release of `json-iterator`:
```
bash-4.3# cat /go/src/k8s.io/test-infra/Gopkg.lock | grep -B1 -A3 json-iterator
[[projects]]
  name = "github.com/json-iterator/go"
  packages = ["."]
  revision = "3353055b2a1a5ae1b6a8dfde887a524e7088f3a2"
  version = "1.1.2"
```
Which is patched in a commit post `json-iterator` v.1.1.2:
https://github.com/json-iterator/go/commit/d51e841de09d234a64d0dfadd2305596979559da

This doesn't look like it affects go 1.9 however:
```
bash-4.3# go version
go version go1.9.4 linux/amd64

bash-4.3# go get -u k8s.io/test-infra/kubetest
bash-4.3#
```

**Comment by BenTheElder** [comment]
sync.Map was added in go 1.9, test-infra builds with go 1.9.3 currently in
conjunction with kubernetes.

**Comment by cjschaef** [comment]
Does this mean that a patch isn't expected, since go 1.9 is the default?

**Comment by BenTheElder** [comment]
I think probably not immediately. IIRC json-iterator is an indirect
dependency we should probably update with it's parent deps.

We build most of this repo with bazel and pin our go version, I don't think
we intend to support go much older than kubernetes's master version. We
should actually upgrade to go 1.10 soon once kubernetes release 1.10 is
done.

**Comment by cjschaef** [comment]
That's too bad, but I guess that's what happens when you work with kube 1.8 (and go 1.8) still. Thanks for the info @BenTheElder.

It would still be nice to see this patched in the future though, if/when `json-iterator` sees a new release b/c of 1.8

**Comment by BenTheElder** [comment]
FWIW If you follow https://github.com/kubernetes/test-infra#building-and-testing-the-test-infra things will just work regardless of the system-wide go version, because of:
https://github.com/kubernetes/test-infra/blob/c3e640a330599cabfbe506e491c1001f4dfec139/WORKSPACE#L21-L23

**Comment by krzyzacy** [comment]
you can consider `bazel run //kubetest` which will pick up the right go version from WORKSPACE

**Comment by cjschaef** [comment]
Okay, something to look into for additional possibilities in the mean time. Think I may be a bit limited to options, but something I'll have to investigate further. Thanks!

**Comment by BenTheElder** [comment]
go 1.10 has been out for a while now 1.8 is fairly old. soon supported kubernetes releases will be well beyond go 1.8
